server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /api/auth/${segment}

        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/api/events/**
          filters:
            - RewritePath=/api/events/(?<segment>.*), /api/events/${segment}

        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/bookings/**
          filters:
            - RewritePath=/api/bookings/(?<segment>.*), /api/bookings/${segment}

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**
          filters:
            - RewritePath=/api/payments/(?<segment>.*), /api/payments/${segment}

jwt:
  secret: MySecretKeyForEventTicketingSystemJWT2026ThisShouldBeLongAndSecureAtLeast256Bits
